using UnityEditor;
namespace Pixyz.Toolbox.Editor {

	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -20)]
		public static void A04f08606_89a0_4a8a_9124_08c0ed65fadb() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -19)]
		public static void Afd0b1ff8_cb51_48af_9d5b_2e2eb727e454() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -18)]
		public static void A733b2293_80df_43a8_96f9_f3664ce8d7d5() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -17)]
		public static void A83be95b9_0780_44a2_8523_fdf60eb8437e() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -15)]
		public static void A5e6cf271_0964_4d6c_9b43_4c7a099043ad() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -14)]
		public static void Aa67223b2_8682_49ef_a8b7_0ad772d7be76() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -13)]
		public static void Aec250fbd_7abf_41cb_bb26_bebe7d77590a() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -12)]
		public static void A406d7545_b0c7_4cb8_ab73_8db1ecda8ec2() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -12)]
		public static void A70c06412_f830_4b8f_be70_04fb21350e08() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -11)]
		public static void A98dcf1bb_32c1_4e06_aae1_2865c41c3ba7() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -10)]
		public static void Af1b3e7da_a63a_48dc_a8bb_861ad9fc9ba0() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -9)]
		public static void Ae70bf2c2_fb7e_4cfa_b3ba_723675d1215d() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -8)]
		public static void Ace7547ec_9102_40ba_9e27_585a85102ae9() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -7)]
		public static void A862671d2_fb38_4d2c_a2ae_31006b419939() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -6)]
		public static void A33838f4d_63ea_4dbe_bb2d_49a2edd88c58() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -5)]
		public static void A8c238bbf_d53a_44a3_9f37_8a7a915eb2d5() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -4)]
		public static void A694f1cf2_ed70_4fe3_b68e_5b3b0d19e8b9() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -3)]
		public static void Acbc27795_4797_4e45_b082_04ff071f9285() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateLightmapUVs()); }

	}
}